# Generated by Django 2.2.9 on 2020-01-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, help_text='Enter your GitHub URL')),
                ('snapchat', models.URLField(blank=True, help_text='Enter your Snapchat URL')),
                ('instagram', models.URLField(blank=True, help_text='Enter a Instagram URL')),
                ('linkedin', models.URLField(blank=True, help_text='Enter a LinkedIn URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
