# Generated by Django 2.2.11 on 2020-03-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter a Facebook URL'),
        ),
    ]
