# Generated by Django 2.2.12 on 2020-05-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_seosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='social_sharing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
