# Generated by Django 2.2.9 on 2020-01-18 05:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='body',
            field=wagtail.core.fields.StreamField([('lesson_highlight', wagtail.core.blocks.StructBlock([('text_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('content', wagtail.core.blocks.RichTextBlock(features=['h3', 'link', 'bold', 'italic'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Read More', max_length=50)), ('internal_link', wagtail.core.blocks.PageChooserBlock(help_text='Select an internal page to link to. Internal links are used before external links (if both are provided).', required=False)), ('external_link', wagtail.core.blocks.URLBlock(help_text='Type an external website to link to. Internal links are used before external links (if both are provided).', required=False))]))]))], blank=True, null=True),
        ),
    ]
